package com.csye6225.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
/**
 * @author Rexus
 * @date 11/10/19
 */
@DynamoDBTable(tableName = "Announcements")
public class Announcements {

    private String Id;
    private String announcementId;
    private String announcementText;
    private String boardId;

    public Announcements() {

    }

    public Announcements(String id, String announcementId, String announcementText, String boardId) {
        Id = id;
        this.announcementId = announcementId;
        this.announcementText = announcementText;
        this.boardId = boardId;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexRangeKey(attributeName = "announcementId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getAnnouncementId() {
        return announcementId;
    }

    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName = "announcementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "boardId-announcementId-index")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }
}
