package com.csye6225.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
/**
 * @author Rexus
 * @date 11/10/19
 */
@DynamoDBTable(tableName = "Board")
public class Board {

    private String Id;
    private String boardId;
    private String courseId;

    public Board() {
    }

    public Board(String id, String boardId, String courseId) {
        Id = id;
        this.boardId = boardId;
        this.courseId = courseId;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "boardId-index")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
}
