package com.csye6225.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.List;
/**
 * @author Rexus
 * @date 2019-10-18
 */
@DynamoDBTable(tableName = "Course")
public class Course {

    private String Id;
    private String courseId;
    private String name;
    private String boardId;
    private String department;
    private List<String> roster;
    private String professorId;
    private String taId;

    public Course(){

    }

    public Course(String id, String courseId, String name, String boardId, String department, List<String> roster, String professorId, String taId) {
        Id = id;
        this.courseId = courseId;
        this.name = name;
        this.boardId = boardId;
        this.department = department;
        this.roster = roster;
        this.professorId = professorId;
        this.taId = taId;
    }
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId-index")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "roster")
    public List<String> getRoster() {
        return roster;
    }

    public void setRoster(List<String> roster) {
        this.roster = roster;
    }
    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }
    @DynamoDBAttribute(attributeName = "taId")
    public String getTaId() {
        return taId;
    }

    public void setTaId(String taId) {
        this.taId = taId;
    }
    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }
}
