package com.csye6225.datamodel;

/**
 * @author Rexus
 * @date 2019-10-18
 */

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName="Professor")
public class Professor {
    private String id;
    private String firstName;
    private String lastName;
    private String department;
    private String professorId;
    private String joiningDate;

    public Professor() {

    }

    public Professor(String Id, String professorId, String firstName,
                     String lastName, String department, String joiningDate) {
        Id = id;
        this.professorId = professorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.department = department;
        this.joiningDate = joiningDate;
    }


    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) { this.id = id; }
    @DynamoDBAttribute(attributeName="firstName")
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    @DynamoDBAttribute(attributeName="lastName")
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    @DynamoDBAttribute(attributeName="department")
    public String getDepartment() {
        return department;
    }
    public void setDepartment(String department) {
        this.department = department;
    }
    @DynamoDBIndexHashKey(attributeName="professorId", globalSecondaryIndexName = "professorId-index")
    public String getProfessorId() {
        return professorId;
    }
    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }
    @DynamoDBAttribute(attributeName="joiningDate")
    public String getJoiningDate() {
        return joiningDate;
    }
    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }


    @DynamoDBIgnore
    @Override
    public String toString() {
        return "Professor{" +
                "id='" + id + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", department='" + department + '\'' +
                ", professorId='" + professorId + '\'' +
                ", joiningDate='" + joiningDate + '\'' +
                '}';
    }
}

